### ISSUE TITLE
NeruIPS23 missing paper: STORM

### ISSUE THREAD

**Issue by weipu-zhang** [opendilab/awesome-model-based-RL#34]
Hi,

Could you please add this paper to your repo?

Title: STORM: Efficient Stochastic Transformer based World Models for Reinforcement Learning

Authors: Weipu Zhang, Gang Wang,Jian Sun, Yetian Yuan, Gao Huang

[OpenReview Link](https://openreview.net/forum?id=WxnrX42rnS)

[Github Link](https://github.com/weipu-zhang/STORM)

Thanks in advance!

**Comment by jiaruonan** [comment]
Thanks for the suggestion!
